name: Create release

on: [push]

jobs:
    create-release:
        runs-on: ubuntu-latest
        steps:
            - name: Get current date
              id: date
              run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
            - name: Test with environment variables
              run: echo $TAG_NAME - $RELEASE_NAME
              env:
                  TAG_NAME: nightly-tag-${{ steps.date.outputs.date }}-${{ github.sha }}
                  RELEASE_NAME: nightly-release-${{ steps.date.outputs.date }}-${{ github.sha }}
            - uses: actions/checkout@v3
            - name: Release snapshot
              id: release-snapshot
              uses: actions/create-release@latest
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: nightly-tag-${{ steps.date.outputs.date }}-${{ github.sha }}
                  release_name: Nightly ${{ steps.date.outputs.date }} (${{ github.sha }})
                  draft: false
                  prerelease: true
